### ISSUE TITLE
Unicode is not working correctly

### ISSUE THREAD

**Issue by bessarabov** [vti/showmetheshell#1]
I have some strange behaviour with unicode symbols.

I open localhost:3000 and cat file with russian letters, but the system does not show me the symbols correctly:
{{{
sh-3.2$ cat unicode
ÐÐÐÐÐÐ
sh-3.2$
}}}

But when I hit "refresh", the screen changes to normal:
{{{
sh-3.2$
АБВГДЕ
sh-3.2$
}}}

But If I try to cat file one more time, I get just the same incorrect behaviour.

I'm using browser:
Chrome 5.0.375.55
Mozilla5.0 Macintosh; U; Intel Mac OS X 10_6_3; en-US AppleWebKit533.4 KHTML, like Gecko Chrome5.0.375.55 Safari533.4

**Comment by vti** [comment]
That's a bug. I will try to fix it ASAP. Thanks.

**Comment by bessarabov** [comment]
Uhoo! =) The unicode in woring perfectly after commit http://github.com/vti/showmetheshell/commit/5c2a7e8b04d836f84273ed06fe665ae7afaeec6b Thank you! (This is the ASAP as it should always be =)
