### ISSUE TITLE
Howto start?

### ISSUE THREAD

**Issue by Lakshmipathi** [vti/showmetheshell#4]
I followed the Installation steps -
" git clone http://github.com/vti/showmetheshell.git sudo cpan -i IO::Pty Term::VT102 JSON cd showmetheshell perl showmetheshell " and Pointed the browser to file://where/you/put/showmetheshell/public/index.html

On the browser , I can see "disconnected" and nothing else. How to install/start using it ?
On the demo viedo, I have seen something like localhost:3000 . I'm confused about how to use ?
Please update,INSTALL file ,if its not complete.

**Comment by Lakshmipathi** [comment]
by mistake,I closed the previous post.sorry,for the double post

**Comment by vti** [comment]
I have rewritten showmetheshell for using SocketIO. I will try to push it today. There will be new instructions :)

**Comment by Lakshmipathi** [comment]
thanks :D

**Comment by vti** [comment]
Please, give it a try now.

**Comment by Lakshmipathi** [comment]
installed the dependencies "cpan IO::Pty Term::VT102 JSON Plack Twiggy Plack::Middleware::SocketIO" started it as "twiggy showmetheshell.psgi" - checked with FF and chrome at http://localhost:5000/ both shows "Connecting..." but nothing more.  Checked the apache error/access logs  no luck.I'm using Fedora 12 ,perl, v5.10.0

**Comment by vti** [comment]
Apache has nothing to do with it, because you're using a standalone server. Connecting state can take some time for the first time, since it is trying to find an appropriate transport...

Better if you post here the log that is printed on the console where you run showmetheshell.

**Comment by Lakshmipathi** [comment]
Continues to say "connecting" - I can't see any log messages at console. netstat says this -

# netstat -antlp | grep 5000

tcp        0      0 0.0.0.0:5000                0.0.0.0:\*                   LISTEN      4561/twiggy       

I can use telnet to access the port

# telnet 127.0.0.1 5000

Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

any thoughts ?

**Comment by vti** [comment]
Try running this command instead of just `twiggy`:

```
plackup -s twiggy showmetheshell.psgi
```

**Comment by vti** [comment]
Sorry, it should be:

```
plackup -s Twiggy showmetheshell.psgi
```

**Comment by Lakshmipathi** [comment]
here is the output

# plackup -s Twiggy showmetheshell.psgi

Twiggy: Accepting connections at http://0.0.0.0:5000/
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET / HTTP/1.1" 200 2600 "-" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /styles.css HTTP/1.1" 200 1436 "http://localhost:5000/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /jquery.js HTTP/1.1" 200 72174 "http://localhost:5000/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /jquery.json.js HTTP/1.1" 200 2247 "http://localhost:5000/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /shell.js HTTP/1.1" 200 3130 "http://localhost:5000/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"
127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /socket.io/socket.io.js HTTP/1.1" 404 9 "http://localhost:5000/" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"

## 127.0.0.1 - - [19/Apr/2011 22:46:19] "GET /favicon.ico HTTP/1.1" 404 9 "-" "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.43 Safari/532.5"

**Comment by vti** [comment]
Ok, so here is the problem

```
GET /socket.io/socket.io.js HTTP/1.1" 404
```

It can't find socket.io library, look at contrib/socket.io directory, is it empty? If yes, run

```
git submodule update --init
```

Check if htdocs/socket.io directory contains broken symlinks. Maybe the problem is actually in those symlinks :(

**Comment by Lakshmipathi** [comment]
Yes,submodule update installs the missing files. Now  I can get the shell. thanks.
