### ISSUE TITLE
porting to mojolicious

### ISSUE THREAD

**Issue by Prajithp** [vti/showmetheshell#6]
is it possible to use Handler.pm and Terminal.pm in Mojolicious directly? if no, do you have any suggestions on this?

**Comment by vti** [comment]
It used to be written in Mojo. See for example anything below this commit: https://github.com/vti/showmetheshell/commit/15e2aedeea22a3a17479f53cfd47f7cb4decee08

**Comment by Prajithp** [comment]
@vti Thank you so much. looking in to that

**Comment by Prajithp** [comment]
Is it possible to kill the child pid when the client or server close the web socket connection?

 I tried kill ``` kill TERM => $pid;```  but it doesn't terminating  the pid

**Comment by vti** [comment]
There are so many things. Like, for example, $pid is not the correct process.

**Comment by Prajithp** [comment]
Thank you @vti 

Ported to mojolicious and it works very nicely.

https://github.com/Prajithp/mojo-terminal
